# your-repo/action.yml
name: My action
author: My name
description: My description

inputs:
  registry:
    description: 'Registry host (e.g. ghcr.io, docker.io)'
    required: false
  name:
    description: 'Repository name (e.g. library/alpine)'
    required: true
  username:
    description: 'Registry username (optional, for private registries)'
    required: false
  password:
    description: 'Registry password (optional, for private registries)'
    required: false

runs:
  using: docker
  image: docker://ghcr.io/sathirak/container-registry-cleaner:latest