# your-repo/action.yml
name: My action
author: My name
description: My description

inputs:
  registry:
    description: 'Registry type'
    required: true
    type: choice
    options:
      - ghcr
      - dockerhub
      - digitalocean
  name:
    description: 'Repository name (e.g. library/alpine)'
    required: true
  username:
    description: 'Registry username (optional, for private registries)'
    required: true
  password:
    description: 'Registry password (optional, for private registries)'
    required: true
  max-images:
    description: 'Maximum number of images to keep'
    required: true

runs:
  using: docker
  image: Dockerfile