name: Test My Go Action

on:
  push:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sathirak/container-registry-cleaner@v1
        with:
          registry: 'ghcr.io'
          name: 'library/alpine'
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
