name: Test My Go Action

on: [push, 'workflow_dispatch']

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sathirak/container-registry-cleaner@v2
        with:
          name: 'library/alpine'
