name: Test My Go Action

on:
  push:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sathirak/container-registry-cleaner@latest
        with:
          registry: 'ghcr.io'
          name: 'sathirak/container-registry-cleaner'
          username: 'sathirak'
          password: ${{ secrets.GITHUB_TOKEN }}
